[templates.ags]
input_path = '~/.config/matugen/templates/ags.scss'
output_path = '~/.config/ags/styles/colors.scss'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock.conf'
output_path = '~/.config/hypr/hyprlock.conf'

[templates.hyprland]
input_path = '~/.config/matugen/templates/colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.vesktop]
input_path = '~/.config/matugen/templates/voidarium.theme.css'
output_path = '~/.config/vesktop/themes/voidarium.theme.css'

[templates.gradience]
input_path = '~/.config/matugen/templates/gradience.json'
output_path = '~/.cache/voidarium/gradience.json'

[templates.vscode]
input_path = '~/.config/matugen/templates/vscode.json'
output_path = '~/.cache/voidarium/vscode.json'

[config]
reload_apps = false
set_wallpaper = false